### ISSUE TITLE
How can I select only text nodes with element prop?

### ISSUE THREAD

**Issue by cihad** [privatenumber/vue-subslot#132]
It seems that such a feature is not supported.

[https://codesandbox.io/s/broken-pond-7v199?file=/src/components/AppButton.vue:135-191](https://codesandbox.io/s/broken-pond-7v199?file=/src/components/AppButton.vue:135-191)

**Comment by privatenumber** [comment]
Thanks for reporting this @cihad 

It's fixed and released in v1.2.3.

You can pick all text nodes like this:
```
<subslot not element="*" />
```

**Comment by cihad** [comment]
Very useful. Thanks.
